name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Create .env file
        run: |
          echo "APP_USERNAME=${{ secrets.APP_USERNAME }}" >> .env
          echo "APP_PASSWORD=${{ secrets.APP_PASSWORD }}" >> .env

      - name: Run Pytest tests
        run: |
          pytest -n auto --alluredir=allure-results

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
